<a href="https://colab.research.google.com/github/danamelissamendoza/Talleres-del-curso-IA-aplicada-a-la-economia/blob/main/Taller_combinaciones_Ordo%C3%B1ez_Rodriguez_Mendoza.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import os
import glob
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
pd.options.display.max_columns = None
pd.options.display.float_format = '{:,.2f}'.format

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [4]:
path = '/content/drive/MyDrive/granencuesta'
os.chdir(path)

In [5]:
print("📂 Carpetas disponibles:\n")
for carpeta in sorted(os.listdir(path)):
    print(f"   📁 {carpeta}")

📂 Carpetas disponibles:

   📁 2025-01-14 Correlativa CIIU Rev4.xlsx
   📁 2025-01-14 DIVIPOLA.xlsx
   📁 Agosto 2025
   📁 GEIH_semestre2_2025.csv
   📁 GEIH_semestre2_2025_limpia.csv
   📁 JULIO 2025
   📁 Septiembre 2025
   📁 diciembre
   📁 noviembre
   📁 octubre

In [6]:
for carpeta in sorted(os.listdir(path)):
    ruta_carpeta = os.path.join(path, carpeta)
    if os.path.isdir(ruta_carpeta) and len(os.listdir(ruta_carpeta)) > 0:
        print(f"\n📁 {carpeta}:")
        for archivo in sorted(os.listdir(ruta_carpeta)):
            print(f"   {repr(archivo)}")

📁 Agosto 2025:
   'Características generales, seguridad social en salud y\xa0 educación.CSV'
   'Datos del hogar y la vivienda.CSV'
   'Fuerza de trabajo.CSV'
   'Migración.CSV'
   'No ocupados.CSV'
   'Ocupados.CSV'
   'Otras formas de trabajo.CSV'
   'Otros ingresos e impuestos.CSV'

📁 JULIO 2025:
   'Características generales, seguridad social en salud y educación.CSV'
   'Datos del hogar y la vivienda.CSV'
   'Fuerza de trabajo.CSV'
   'Migración.CSV'
   'No ocupados.CSV'
   'Ocupados.CSV'
   'Otras formas de trabajo.CSV'
   'Otros ingresos e impuestos.CSV'

📁 Septiembre 2025:
   'Características generales, seguridad social en salud y educación.CSV'
   'Datos del hogar y la vivienda.CSV'
   'Fuerza de trabajo.CSV'
   'Migración.CSV'
   'No ocupados.CSV'
   'Ocupados.CSV'
   'Otras formas de trabajo.CSV'

📁 diciembre:
   'Características generales, seguridad social en salud y educación.CSV'
   'Datos\xa0del hogar y\xa0la\xa0vivienda.CSV'
   'Fuerza\xa0de\xa0trabajo.CSV'
   'Migración.CSV'
   'No ocupados.CSV'
   'Ocupados.CSV'
   'Otras formas\xa0de\xa0trabajo.CSV'
   'Otros ingresos e impuestos.CSV'

📁 noviembre:
   'Características generales, seguridad social en salud y educación.CSV'
   'Datos del hogar y la vivienda.CSV'
   'Fuerza de trabajo.CSV'
   'Migración.CSV'
   'No ocupados.CSV'
   'Ocupados.CSV'
   'Otras formas de trabajo.CSV'
   'Otros ingresos e impuestos.CSV'

📁 octubre:
   'Características generales, seguridad social en salud y educación.CSV'
   'Datos del hogar y la vivienda.CSV'
   'Fuerza de trabajo.CSV'
   'Migración.CSV'
   'No ocupados.CSV'
   'Ocupados.CSV'
   'Otras formas de trabajo.CSV'
   'Otros ingresos e impuestos.CSV'

In [14]:
def encontrar_archivo(ruta_carpeta, patron):


    for archivo in archivos:

        archivo_limpio = archivo.replace('\xa0', ' ').strip()
        if patron.lower() in archivo_limpio.lower():
            return os.path.join(ruta_carpeta, archivo)
    return None

LLAVES_PERSONA = ['DIRECTORIO', 'SECUENCIA_P', 'ORDEN']

LLAVES_HOGAR   = ['DIRECTORIO', 'SECUENCIA_P']


PARAMS_CSV = {
    'sep'       : ';',
    'encoding'  : 'latin-1',
    'low_memory': False
}


PATRON_A = 'Características generales'
PATRON_B = 'hogar y la vivienda'
PATRON_C = 'Fuerza de trabajo'
PATRON_D = 'Ocupados'

In [15]:
import unicodedata

def normalizar(texto):

    texto = texto.replace('\xa0', ' ').strip()
    texto = unicodedata.normalize('NFD', texto)
    texto = ''.join(c for c in texto if unicodedata.category(c) != 'Mn')
    return texto.lower()

def encontrar_archivo(ruta_carpeta, patron):

    patron_normalizado = normalizar(patron)
    for archivo in os.listdir(ruta_carpeta):
        if patron_normalizado in normalizar(archivo):
            return os.path.join(ruta_carpeta, archivo)
    return None

# Las llaves que identifican a cada persona en la GEIH
LLAVES_PERSONA = ['DIRECTORIO', 'SECUENCIA_P', 'ORDEN']
LLAVES_HOGAR   = ['DIRECTORIO', 'SECUENCIA_P']

# Parámetros comunes para todos los read_csv
PARAMS_CSV = {
    'sep'       : ';',
    'encoding'  : 'latin-1',
    'low_memory': False
}

# Patrones sin tildes para evitar problemas de codificación
PATRON_A = 'Caracteristicas generales'
PATRON_B = 'hogar y la vivienda'
PATRON_C = 'Fuerza de trabajo'
PATRON_D = 'Ocupados'

# Verificación rápida en Julio
ruta_julio = os.path.join(path, 'JULIO 2025')
print("🔍 Prueba en Julio:")
print(f"  A: {encontrar_archivo(ruta_julio, PATRON_A)}")
print(f"  B: {encontrar_archivo(ruta_julio, PATRON_B)}")
print(f"  C: {encontrar_archivo(ruta_julio, PATRON_C)}")
print(f"  D: {encontrar_archivo(ruta_julio, PATRON_D)}")

🔍 Prueba en Julio:
  A: /content/drive/MyDrive/granencuesta/JULIO 2025/Características generales, seguridad social en salud y educación.CSV
  B: /content/drive/MyDrive/granencuesta/JULIO 2025/Datos del hogar y la vivienda.CSV
  C: /content/drive/MyDrive/granencuesta/JULIO 2025/Fuerza de trabajo.CSV
  D: /content/drive/MyDrive/granencuesta/JULIO 2025/Ocupados.CSV

In [16]:
# Nombres exactos de carpetas tal como aparecen en Drive
meses = {
    'Julio'      : 'JULIO 2025',
    'Agosto'     : 'Agosto 2025',
    'Septiembre' : 'Septiembre 2025',
    'Octubre'    : 'octubre',
    'Noviembre'  : 'noviembre',
    'Diciembre'  : 'diciembre'
}

lista_bases = []

for etiqueta, nombre_carpeta in meses.items():

    ruta_mes = os.path.join(path, nombre_carpeta)


    if not os.path.exists(ruta_mes) or len(os.listdir(ruta_mes)) == 0:
        print(f"⚠️  {etiqueta}: carpeta vacía o no encontrada, se omite.\n")
        continue

    print(f"\n{'='*55}")
    print(f"Procesando: {etiqueta}")
    print(f"{'='*55}")


    ruta_a = encontrar_archivo(ruta_mes, PATRON_A)
    ruta_b = encontrar_archivo(ruta_mes, PATRON_B)
    ruta_c = encontrar_archivo(ruta_mes, PATRON_C)
    ruta_d = encontrar_archivo(ruta_mes, PATRON_D)


    faltantes = [n for n, r in [('A', ruta_a), ('B', ruta_b),
                                 ('C', ruta_c), ('D', ruta_d)] if r is None]
    if faltantes:
        print(f"Módulos no encontrados: {faltantes}, se omite el mes.")
        continue


    df_a = pd.read_csv(ruta_a, **PARAMS_CSV)
    df_b = pd.read_csv(ruta_b, **PARAMS_CSV)
    df_c = pd.read_csv(ruta_c, **PARAMS_CSV)
    df_d = pd.read_csv(ruta_d, **PARAMS_CSV)


    df_a.columns = df_a.columns.str.upper().str.strip()
    df_b.columns = df_b.columns.str.upper().str.strip()
    df_c.columns = df_c.columns.str.upper().str.strip()
    df_d.columns = df_d.columns.str.upper().str.strip()

    print(f"Módulo A (Características): {df_a.shape[0]:,} filas")
    print(f"Módulo B (Hogar):           {df_b.shape[0]:,} filas")
    print(f"Módulo C (Fuerza trabajo):  {df_c.shape[0]:,} filas")
    print(f"Módulo D (Ocupados):        {df_d.shape[0]:,} filas")


    base = pd.merge(df_a, df_b, on=LLAVES_HOGAR,  how='left', suffixes=('', '_drop'))
    base = pd.merge(base, df_c, on=LLAVES_PERSONA, how='left', suffixes=('', '_drop'))
    base = pd.merge(base, df_d, on=LLAVES_PERSONA, how='left', suffixes=('', '_drop'))


    cols_drop = [c for c in base.columns if c.endswith('_drop')]
    base.drop(columns=cols_drop, inplace=True)


    base['MES'] = etiqueta

    print(f"\n  🔗 Base unida: {base.shape[0]:,} personas × {base.shape[1]} variables")

    lista_bases.append(base)

print("\n✅ Procesamiento terminado.")

=======================================================
Procesando: Julio
=======================================================
Módulo A (Características): 68,436 filas
Módulo B (Hogar):           24,546 filas
Módulo C (Fuerza trabajo):  54,630 filas
Módulo D (Ocupados):        30,153 filas

  🔗 Base unida: 68,436 personas × 312 variables

=======================================================
Procesando: Agosto
=======================================================
Módulo A (Características): 68,577 filas
Módulo B (Hogar):           24,609 filas
Módulo C (Fuerza trabajo):  54,791 filas
Módulo D (Ocupados):        24,636 filas

  🔗 Base unida: 68,577 personas × 147 variables

=======================================================
Procesando: Septiembre
=======================================================
Módulo A (Características): 68,263 filas
Módulo B (Hogar):           24,524 filas
Módulo C (Fuerza trabajo):  54,543 filas
Módulo D (Ocupados):        24,355 filas

  🔗 Base unida: 68,263 personas × 147 variables

=======================================================
Procesando: Octubre
=======================================================
Módulo A (Características): 68,710 filas
Módulo B (Hogar):           24,774 filas
Módulo C (Fuerza trabajo):  55,085 filas
Módulo D (Ocupados):        30,807 filas

  🔗 Base unida: 68,710 personas × 312 variables

=======================================================
Procesando: Noviembre
=======================================================
Módulo A (Características): 68,582 filas
Módulo B (Hogar):           24,724 filas
Módulo C (Fuerza trabajo):  55,008 filas
Módulo D (Ocupados):        30,939 filas

  🔗 Base unida: 68,582 personas × 312 variables

=======================================================
Procesando: Diciembre
=======================================================
Módulo A (Características): 66,559 filas
Módulo B (Hogar):           24,159 filas
Módulo C (Fuerza trabajo):  53,461 filas
Módulo D (Ocupados):        29,611 filas

  🔗 Base unida: 66,559 personas × 312 variables

✅ Procesamiento terminado.

In [17]:
df_geih = pd.concat(lista_bases, axis=0, ignore_index=True)

print(f"Base semestral GEIH 2025:")
print(f"   Total personas-mes: {df_geih.shape[0]:,}")
print(f"   Total variables:    {df_geih.shape[1]}")

Base semestral GEIH 2025:
   Total personas-mes: 409,127
   Total variables:    336

In [18]:
print("Registros por mes:")
display(df_geih['MES'].value_counts(dropna=False))

Registros por mes:

MES
Octubre       68710
Noviembre     68582
Agosto        68577
Julio         68436
Septiembre    68263
Diciembre     66559
Name: count, dtype: int64

In [192]:
df_geih.head(3)

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,PT,P6016,P3271,P6040,P6030S1,P6030S3,P6050,P6083,P6083S1,P6081,P6081S1,P2057,P2059,P2061,P6080,P6080S1,P6080S1A1,P6070,P6071,P6071S1,P6090,P6100,P6110,P6120,P1906S1,P1906S2,P1906S3,P1906S4,P1906S5,P1906S6,P1906S7,P1906S8,P6160,P6170,P3041,P3042,P3042S1,P3042S2,P3043,P3043S1,P3038,P3039,POB_MAY18,P4005,P4010,P4020,P4030S1,P4030S1A1,P4030S2,P4030S3,P4030S4,P4030S4A1,P4030S5,P70,P5000,P5010,P5020,P5030,P5040,P5050,P5070,P5080,P5090,P5090S1,P5100,P5110,P5130,P5140,P5222S1,P5222S2,P5222S3,P5222S4,P5222S5,P5222S6,P5222S7,P5222S8,P5222S8A1,P5222S9,P5222S10,P5222S11,P6008,FT,FFT,PET,P6240,P6240S1,P6240S2,P6250,P6260,P6260S1,P6260S1A1,P6260S2,P6270,P6280,P3362S1,P3362S2,P3362S3,P3362S4,P3362S5,P3362S6,P3362S7,P3362S8,P3362S7A1,P6300,P6310,P6310S1,P6320,P6330,P6340,P6350,P6351,P3044S2,P6440,P6450,P6460,P6460S1,P6400,P6410,P6422,P6420S2,P6424S1,P6424S2,P6424S3,P6424S5,P6426,P6430,P6430S1,P3045S1,P3045S2,P3045S3,P3046,P3363,P9440,P6500,P3364,P3364S1,P6510,P6510S1,P6510S2,P6590,P6590S1,P6600,P6600S1,P6610,P6610S1,P6620,P6620S1,P6585S1,P6585S1A1,P6585S1A2,P6585S2,P6585S2A1,P6585S2A2,P6585S3,P6585S3A1,P6585S3A2,P6585S4,P6585S4A1,P6585S4A2,P6545,P6545S1,P6545S2,P6580,P6580S1,P6580S2,P6630S1,P6630S1A1,P6630S2,P6630S2A1,P6630S3,P6630S3A1,P6630S4,P6630S4A1,P6630S6,P6630S6A1,P6640,P6640S1,P1800,P1800S1,P1801S1,P1801S2,P1801S3,P1802,P3047,P3048,P3049,P6765,P6765S1,P3051,P3052,P3053,P3365,P3365S1,P3054,P3054S1,P3055,P3055S1,P3056,P3057,P6760,P3058S1,P3058S2,P3058S3,P3058S4,P3058S5,P3059,P3061,P3062S1,P3062S2,P3062S3,P3062S4,P3062S5,P3062S6,P3062S7,P3062S8,P3062S9,P3063,P3063S1,P3064,P3064S1,P3065,P3066,P3067,P3067S1,P3067S2,P6775,P3068,P6750,P3073,P550,P6780,P6780S1,P1879,P1805,P6790,P6800,P6810,P6810S1,P6850,P6830,P6830S1,P3069,P6880,P6880S1,P6915,P6915S1,P6920,P6930,P6940,P6960,P6990,P9450,P7020,P760,P7026,P7028,P7028S1,P1880,P1880S1,P7040,P7045,P3071S3,P3072S2,P7050,P7070,P7075,P7077,P7090,P7100,P7110,P7120,P7130,P7140S1,P7140S2,P7140S3,P7140S4,P7140S5,P7140S6,P7140S7,P7140S8,P7140S9,P7140S9A1,P7150,P7160,P7170S1,P7170S5,P7170S6,P7180,P514,P515,P1881,P1881S1,P1882,P7240,P7240S1,OCI,INGLABO,RAMA2D_R4,RAMA4D_R4,OFICIO_C8,DSI,P7250,P7280,P7280S1,P744,P3074,P7260,P1806,P7430,P7440,P7440S1,P7440S2,P7450,P7350,P7360,P9460,P1519,P1883,P7422,P7422S1,OFICIO1_C8,OFICIO2_C8,RAMA2D_D_R4,RAMA4D_D_R4
0,20250731,Julio,2025,8283143,1,1,1,10,NaN,2,27.75,8,1,1,1,72,8.00,"1,952.00",1,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,2.00,1,3.00,NaN,NaN,4,4,4,3,3,4,4,4,2.00,2.00,NaN,1.00,0.00,NaN,NaN,NaN,2.00,1.00,1.00,1,5,1,1,1.00,2,2,2,NaN,2,1,2,1,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,"200,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,2,1.00,NaN,1.00,1.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,143.00,1.00,1.00,NaN,NaN,1.00,NaN,1.00,NaN,2.00,2.00,2.00,2.00,84.00,7.00,NaN,2.00,2.00,2.00,2.00,1.00,2.00,"590,000.00",2.00,NaN,2.00,NaN,NaN,2.00,NaN,1.00,"200,000.00",2.00,NaN,2.00,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,40.00,NaN,NaN,40.00,NaN,NaN,2.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,1.00,0.00,3.00,4.00,NaN,3.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,1.00,2.00,1.00,1.00,3.00,NaN,10.00,3.00,NaN,1.00,"790,000.00",1.00,143.00,"9,212.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20250731,Julio,2025,8283143,1,2,1,10,NaN,2,27.75,8,1,2,2,34,8.00,"1,990.00",2,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,1.00,2,NaN,NaN,NaN,4,4,4,4,4,4,4,4,2.00,2.00,NaN,1.00,0.00,NaN,NaN,NaN,1.00,2.00,1.00,1,5,1,1,1.00,2,2,2,NaN,2,1,2,1,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,"200,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,2,NaN,1.00,1.00,4.00,NaN,NaN,2.00,2.00,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20250731,Julio,2025,8283145,1,1,1,10,NaN,2,59.11,8,1,1,1,45,6.00,"1,980.00",1,3,NaN,2,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,2.00,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,3.00,1.00,NaN,NaN,NaN,2.00,1.00,1.00,1,2,1,1,1.00,2,2,2,NaN,2,1,3,2,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,"100,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,4,1.00,NaN,1.00,1.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,141.00,1.00,1.00,NaN,NaN,1.00,NaN,1.00,NaN,2.00,2.00,2.00,2.00,48.00,1.00,NaN,2.00,2.00,2.00,2.00,1.00,2.00,"1,000,000.00",2.00,NaN,2.00,NaN,NaN,2.00,NaN,1.00,"100,000.00",2.00,NaN,2.00,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,70.00,NaN,NaN,70.00,NaN,NaN,2.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,1.00,1.00,36.00,7.00,NaN,7.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,2.00,1.00,2.00,1.00,1.00,3.00,NaN,4.00,8.00,NaN,1.00,"1,100,000.00",1.00,141.00,"1,311.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
duplicados = df_geih.duplicated(subset=LLAVES_PERSONA).sum()
print(f"Duplicados en llaves: {duplicados:,}")

Duplicados en llaves: 0

In [21]:
print("RESUMEN BASE COMPLETA GEIH - Semestre 2 2025")
print("="*50)
print(f"   Total personas-mes: {df_geih.shape[0]:,}")
print(f"   Total variables:    {df_geih.shape[1]}")
print(f"   Meses incluidos:    {df_geih['MES'].nunique()}")

RESUMEN BASE COMPLETA GEIH - Semestre 2 2025
==================================================
   Total personas-mes: 409,127
   Total variables:    336
   Meses incluidos:    6

In [22]:
print("Registros por mes:")
display(df_geih['MES'].value_counts(dropna=False))

Registros por mes:

MES
Octubre       68710
Noviembre     68582
Agosto        68577
Julio         68436
Septiembre    68263
Diciembre     66559
Name: count, dtype: int64

In [23]:
df_geih.head(3)

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,FEX_C18,DPTO,PT,P6016,P3271,P6040,P6030S1,P6030S3,P6050,P6083,P6083S1,P6081,P6081S1,P2057,P2059,P2061,P6080,P6080S1,P6080S1A1,P6070,P6071,P6071S1,P6090,P6100,P6110,P6120,P1906S1,P1906S2,P1906S3,P1906S4,P1906S5,P1906S6,P1906S7,P1906S8,P6160,P6170,P3041,P3042,P3042S1,P3042S2,P3043,P3043S1,P3038,P3039,POB_MAY18,P4005,P4010,P4020,P4030S1,P4030S1A1,P4030S2,P4030S3,P4030S4,P4030S4A1,P4030S5,P70,P5000,P5010,P5020,P5030,P5040,P5050,P5070,P5080,P5090,P5090S1,P5100,P5110,P5130,P5140,P5222S1,P5222S2,P5222S3,P5222S4,P5222S5,P5222S6,P5222S7,P5222S8,P5222S8A1,P5222S9,P5222S10,P5222S11,P6008,FT,FFT,PET,P6240,P6240S1,P6240S2,P6250,P6260,P6260S1,P6260S1A1,P6260S2,P6270,P6280,P3362S1,P3362S2,P3362S3,P3362S4,P3362S5,P3362S6,P3362S7,P3362S8,P3362S7A1,P6300,P6310,P6310S1,P6320,P6330,P6340,P6350,P6351,P3044S2,P6440,P6450,P6460,P6460S1,P6400,P6410,P6422,P6420S2,P6424S1,P6424S2,P6424S3,P6424S5,P6426,P6430,P6430S1,P3045S1,P3045S2,P3045S3,P3046,P3363,P9440,P6500,P3364,P3364S1,P6510,P6510S1,P6510S2,P6590,P6590S1,P6600,P6600S1,P6610,P6610S1,P6620,P6620S1,P6585S1,P6585S1A1,P6585S1A2,P6585S2,P6585S2A1,P6585S2A2,P6585S3,P6585S3A1,P6585S3A2,P6585S4,P6585S4A1,P6585S4A2,P6545,P6545S1,P6545S2,P6580,P6580S1,P6580S2,P6630S1,P6630S1A1,P6630S2,P6630S2A1,P6630S3,P6630S3A1,P6630S4,P6630S4A1,P6630S6,P6630S6A1,P6640,P6640S1,P1800,P1800S1,P1801S1,P1801S2,P1801S3,P1802,P3047,P3048,P3049,P6765,P6765S1,P3051,P3052,P3053,P3365,P3365S1,P3054,P3054S1,P3055,P3055S1,P3056,P3057,P6760,P3058S1,P3058S2,P3058S3,P3058S4,P3058S5,P3059,P3061,P3062S1,P3062S2,P3062S3,P3062S4,P3062S5,P3062S6,P3062S7,P3062S8,P3062S9,P3063,P3063S1,P3064,P3064S1,P3065,P3066,P3067,P3067S1,P3067S2,P6775,P3068,P6750,P3073,P550,P6780,P6780S1,P1879,P1805,P6790,P6800,P6810,P6810S1,P6850,P6830,P6830S1,P3069,P6880,P6880S1,P6915,P6915S1,P6920,P6930,P6940,P6960,P6990,P9450,P7020,P760,P7026,P7028,P7028S1,P1880,P1880S1,P7040,P7045,P3071S3,P3072S2,P7050,P7070,P7075,P7077,P7090,P7100,P7110,P7120,P7130,P7140S1,P7140S2,P7140S3,P7140S4,P7140S5,P7140S6,P7140S7,P7140S8,P7140S9,P7140S9A1,P7150,P7160,P7170S1,P7170S5,P7170S6,P7180,P514,P515,P1881,P1881S1,P1882,P7240,P7240S1,OCI,INGLABO,RAMA2D_R4,RAMA4D_R4,OFICIO_C8,DSI,P7250,P7280,P7280S1,P744,P3074,P7260,P1806,P7430,P7440,P7440S1,P7440S2,P7450,P7350,P7360,P9460,P1519,P1883,P7422,P7422S1,OFICIO1_C8,OFICIO2_C8,RAMA2D_D_R4,RAMA4D_D_R4
0,20250731,Julio,2025,8283143,1,1,1,10,NaN,2,27.75,8,1,1,1,72,8.00,"1,952.00",1,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,2.00,1,3.00,NaN,NaN,4,4,4,3,3,4,4,4,2.00,2.00,NaN,1.00,0.00,NaN,NaN,NaN,2.00,1.00,1.00,1,5,1,1,1.00,2,2,2,NaN,2,1,2,1,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,"200,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,2,1.00,NaN,1.00,1.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,143.00,1.00,1.00,NaN,NaN,1.00,NaN,1.00,NaN,2.00,2.00,2.00,2.00,84.00,7.00,NaN,2.00,2.00,2.00,2.00,1.00,2.00,"590,000.00",2.00,NaN,2.00,NaN,NaN,2.00,NaN,1.00,"200,000.00",2.00,NaN,2.00,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,40.00,NaN,NaN,40.00,NaN,NaN,2.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,1.00,0.00,3.00,4.00,NaN,3.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,1.00,2.00,1.00,1.00,3.00,NaN,10.00,3.00,NaN,1.00,"790,000.00",1.00,143.00,"9,212.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20250731,Julio,2025,8283143,1,2,1,10,NaN,2,27.75,8,1,2,2,34,8.00,"1,990.00",2,3,NaN,3,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,1.00,2,NaN,NaN,NaN,4,4,4,4,4,4,4,4,2.00,2.00,NaN,1.00,0.00,NaN,NaN,NaN,1.00,2.00,1.00,1,5,1,1,1.00,2,2,2,NaN,2,1,2,1,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,"200,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,2,NaN,1.00,1.00,4.00,NaN,NaN,2.00,2.00,NaN,NaN,NaN,2.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20250731,Julio,2025,8283145,1,1,1,10,NaN,2,59.11,8,1,1,1,45,6.00,"1,980.00",1,3,NaN,2,NaN,1,NaN,1,6,NaN,NaN,2.00,1.00,2.00,1,3.00,NaN,NaN,4,4,4,4,4,4,4,4,1.00,2.00,NaN,3.00,1.00,NaN,NaN,NaN,2.00,1.00,1.00,1,2,1,1,1.00,2,2,2,NaN,2,1,3,2,6,NaN,4,6,5,5.00,4,NaN,NaN,NaN,"100,000.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,NaN,NaN,4,1.00,NaN,1.00,1.00,NaN,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,141.00,1.00,1.00,NaN,NaN,1.00,NaN,1.00,NaN,2.00,2.00,2.00,2.00,48.00,1.00,NaN,2.00,2.00,2.00,2.00,1.00,2.00,"1,000,000.00",2.00,NaN,2.00,NaN,NaN,2.00,NaN,1.00,"100,000.00",2.00,NaN,2.00,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,70.00,NaN,NaN,70.00,NaN,NaN,2.00,8.00,NaN,2.00,NaN,2.00,NaN,NaN,NaN,2.00,2.00,1.00,1.00,36.00,7.00,NaN,7.00,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,NaN,NaN,NaN,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,2.00,1.00,2.00,1.00,1.00,3.00,NaN,4.00,8.00,NaN,1.00,"1,100,000.00",1.00,141.00,"1,311.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
df_geih.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 409127 entries, 0 to 409126
Columns: 336 entries, PERIODO to RAMA4D_D_R4
dtypes: float64(268), int64(45), object(23)
memory usage: 1.0+ GB

In [28]:
df_geih.to_csv('GEIH_semestre2_2025.csv', encoding='utf-8', index=False)
print("Base guardada como GEIH_semestre2_2025.csv")

Base guardada como GEIH_semestre2_2025.csv

In [31]:
import requests
url = 'https://github.com/LinaMariaCastro/curso-ia-para-economia/raw/main/datasets/2025-01-14%20Correlativa%20CIIU%20Rev4.xlsx'

response = requests.get(url)

if response.status_code == 200:
    with open('2025-01-14 Correlativa CIIU Rev4.xlsx', 'wb') as f:
        f.write(response.content)
    print("Archivo descargado correctamente")
else:
    print(f"Error: {response.status_code}")

Archivo descargado correctamente

In [32]:
df_ciiu = pd.read_excel('2025-01-14 Correlativa CIIU Rev4.xlsx',
                         sheet_name='CIIU 2022')

print(f"Forma: {df_ciiu.shape}")
print(f"\nColumnas: {df_ciiu.columns.tolist()}")
df_ciiu.head(10)

Forma: (514, 2)

Columnas: ['RAMA4D_R4', 'DESCRIPCION_CIIU']

   RAMA4D_R4                                   DESCRIPCION_CIIU
0          0                                        Desconocido
1         10                       Actividad Personas Naturales
2         20                       Actividad Personas Naturales
3         81                       Actividad Personas Naturales
4         82                       Actividad Personas Naturales
5         90                       Actividad Personas Naturales
6        111  Cultivo de cereales (excepto arroz), legumbres...
7        112                                   Cultivo de arroz
8        113         Cultivo de hortalizas, raíces y tubérculos
9        114                                  Cultivo de tabaco

In [33]:
print(f"Tipo RAMA4D_R4 en df_geih: {df_geih['RAMA4D_R4'].dtype}")
print(f"Tipo RAMA4D_R4 en df_ciiu:  {df_ciiu['RAMA4D_R4'].dtype}")

Tipo RAMA4D_R4 en df_geih: float64
Tipo RAMA4D_R4 en df_ciiu:  int64

In [35]:
df_ciiu['RAMA4D_R4'] = df_ciiu['RAMA4D_R4'].astype('float64')

print(f"Tipo RAMA4D_R4 en df_geih: {df_geih['RAMA4D_R4'].dtype}")
print(f"Tipo RAMA4D_R4 en df_ciiu:  {df_ciiu['RAMA4D_R4'].dtype}")
print("Tipos igualados")

Tipo RAMA4D_R4 en df_geih: float64
Tipo RAMA4D_R4 en df_ciiu:  float64
Tipos igualados

In [36]:
df_geih = pd.merge(df_geih, df_ciiu,
                   on='RAMA4D_R4',
                   how='left')

display(df_geih[['RAMA4D_R4', 'DESCRIPCION_CIIU']].dropna().head(10))

    RAMA4D_R4                                   DESCRIPCION_CIIU
0      143.00                            Cría de ovejas y cabras
2      141.00                   Cría de ganado bovino y bufalino
4      141.00                   Cría de ganado bovino y bufalino
5      161.00              Actividades de apoyo a la agricultura
6    5,022.00                        Transporte fluvial de carga
10   5,022.00                        Transporte fluvial de carga
11   5,630.00  Expendio de bebidas alcohólicas para el consum...
13     113.00         Cultivo de hortalizas, raíces y tubérculos
15   5,619.00  Otros tipos de expendio de comidas preparadas ...
16     113.00         Cultivo de hortalizas, raíces y tubérculos

In [37]:
tiene_ciiu = df_geih['DESCRIPCION_CIIU'].notna().sum()
sin_ciiu   = df_geih['DESCRIPCION_CIIU'].isna().sum()

print(f"✅ Con descripción CIIU:    {tiene_ciiu:,}")
print(f"⚠️  Sin descripción CIIU:   {sin_ciiu:,}")

✅ Con descripción CIIU:    121,510
⚠️  Sin descripción CIIU:   287,617

In [39]:
print(f"Columnas finales de df_geih: {df_geih.shape[1]}")
print(f"\nÚltimas columnas agregadas:")
print(df_geih.columns.tolist()[-5:])

Columnas finales de df_geih: 337

Últimas columnas agregadas:
['OFICIO1_C8', 'OFICIO2_C8', 'RAMA2D_D_R4', 'RAMA4D_D_R4', 'DESCRIPCION_CIIU']

In [91]:
display(df_geih[['DIRECTORIO', 'SECUENCIA_P', 'ORDEN',
                  'RAMA4D_R4', 'DESCRIPCION_CIIU']].head(10))

,DIRECTORIO,SECUENCIA_P,ORDEN,RAMA4D_R4,DESCRIPCION_CIIU
0,8283143,1,1,143.00,Cría de ovejas y cabras
1,8283143,1,2,NaN,NaN
2,8283145,1,1,141.00,Cría de ganado bovino y bufalino
3,8283145,1,2,NaN,NaN
4,8283145,1,3,141.00,Cría de ganado bovino y bufalino
5,8283145,1,4,161.00,Actividades de apoyo a la agricultura
6,8283147,1,1,"5,022.00",Transporte fluvial de carga
7,8283147,1,2,NaN,NaN
8,8283147,1,3,NaN,NaN
9,8283147,1,4,NaN,NaN

In [97]:
url = "https://raw.githubusercontent.com/LinaMariaCastro/curso-ia-para-economia/main/datasets/2025-01-14%20DIVIPOLA.xlsx"

divipola = pd.read_excel(url,
                         sheet_name='Departamentos',
                         skiprows=9)

print(f"Columnas: {divipola.columns.tolist()}")
divipola.head()

Columnas: ['Código', 'Nombre']

  Código        Nombre
0     05     ANTIOQUIA
1     08     ATLÁNTICO
2     11  BOGOTÁ, D.C.
3     13       BOLÍVAR
4     15        BOYACÁ

In [98]:
print(f"Tipo DPTO en df_geih:      {df_geih['DPTO'].dtype}")
print(f"Tipo Código en divipola:   {divipola['Código'].dtype}")


print(f"\nEjemplos DPTO en df_geih: {df_geih['DPTO'].dropna().head(5).tolist()}")
print(f"Ejemplos Código divipola: {divipola['Código'].head(5).tolist()}")

Tipo DPTO en df_geih:      int64
Tipo Código en divipola:   object

Ejemplos DPTO en df_geih: [8, 8, 8, 8, 8]
Ejemplos Código divipola: ['05', '08', '11', '13', 15]

In [99]:
divipola = divipola[pd.to_numeric(divipola['Código'], errors='coerce').notna()]

divipola['Código'] = divipola['Código'].astype('float64')

divipola.columns = ['DPTO', 'NOMBRE_DPTO']

print(f" Divipola limpio: {divipola.shape}")
print(f"Tipo DPTO en df_geih:  {df_geih['DPTO'].dtype}")
print(f"Tipo DPTO en divipola: {divipola['DPTO'].dtype}")
divipola.head()

 Divipola limpio: (33, 2)
Tipo DPTO en df_geih:  int64
Tipo DPTO en divipola: float64

   DPTO   NOMBRE_DPTO
0  5.00     ANTIOQUIA
1  8.00     ATLÁNTICO
2 11.00  BOGOTÁ, D.C.
3 13.00       BOLÍVAR
4 15.00        BOYACÁ

In [105]:
df_geih = pd.merge(df_geih, divipola,
                   on='DPTO',
                   how='left',
                   suffixes=('', '_drop'))
cols_drop = [c for c in df_geih.columns if c.endswith('_drop')]
df_geih.drop(columns=cols_drop, inplace=True)

print(f"✅ Merge realizado: {df_geih.shape}")
display(df_geih[['DPTO', 'NOMBRE_DPTO']].dropna().head(10))

✅ Merge realizado: (409127, 338)

   DPTO NOMBRE_DPTO
0     8   ATLÁNTICO
1     8   ATLÁNTICO
2     8   ATLÁNTICO
3     8   ATLÁNTICO
4     8   ATLÁNTICO
5     8   ATLÁNTICO
6     8   ATLÁNTICO
7     8   ATLÁNTICO
8     8   ATLÁNTICO
9     8   ATLÁNTICO